### ISSUE TITLE
Currently, there is no simple graph option for outputting html format visualization.

### ISSUE THREAD

**Issue by luutuntin** [panx27/amr-reader#1]
Hi Xiaoman,

Thank you so much for this well-written toolkit.
I just have this small remark.
The problem comes out when we want to output the simple graphs and the html format visualization at the same time (e.g. _bin/amr_reader input_dir output_dir -g s -v_). In this case the simple graphs are first created and then unexpectedly replaced by the normal ones.
Thank you for your consideration and please correct me if I have any misunderstanding.

Best,
Alex

**Comment by panx27** [comment]
Hi Alex,

Thank you for your comment. Simple graph option for html visualization has been added. Please try  command: bin/amr_reader input_dir output_dir -v=s
Let me know if you have any questions.

Best,
Xiaoman

**Comment by luutuntin** [comment]
Hi Xiaoman,

Thank you for your lightning response.
I've tried your updated version, it looks great now.

Best,
Alex
