### ISSUE TITLE
Incomplete Vizualisation

### ISSUE THREAD

**Issue by TigranGalstyan** [panx27/amr-reader#2]
Here is an example of AMR graph, taken from AMR_2.0 corpus that's being vizualised incompletely.

      # ::id DF-199-194215-653_0484.5 ::date 2013-09-01T11:38:32 ::annotator SDL-AMR-09 ::preferred
      # ::snt He has too much going on in his life right now and he thinks we can work when I have told him several times I dont love him and he does not love me.
      # ::save-date Thu Dec 17, 2015 ::file DF-199-194215-653_0484_5.txt
      (a / and
            :op1 (g / go-on-15
                  :ARG1 (m / much
                        :degree (t2 / too))
                  :location (l / life
                        :poss (h2 / he))
                  :time (n / now
                        :mod (r / right)))
            :op2 (t / think-01
                  :ARG0 h2
                  :ARG1 (p / possible-01
                        :ARG1 (w / work-09
                              :ARG1 (w2 / we)))
                  :concession (t3 / tell-01
                        :ARG0 (i / i)
                        :ARG1 (a2 / and
                              :op1 (l2 / love-01 :polarity -
                                    :ARG0 i
                                    :ARG1 h2)
                              :op2 (l3 / love-01 :polarity -
                                    :ARG0 h2
                                    :ARG1 i))
                        :ARG2 h2
                        :frequency (s2 / several))))

The nodes l2 (love-01) and l3 (love-01) should have two outgoing edges, but on the vizualisation they don't have any. We suppose it might be because both arguments of l2 or l3 refer to already existing nodes.

![df-199-194215-653_0484 5](https://user-images.githubusercontent.com/8489713/36680727-0b9ca712-1b30-11e8-9439-1cc7e6dd4e1a.png)

**Comment by panx27** [comment]
Hi, thank you very much for you report! This bug has been fixed in https://github.com/panx27/amr-reader/commit/cee7ac05fd84c80ca3caf5943f40a7f4c4dadf39
