### ISSUE TITLE
entity linking

### ISSUE THREAD

**Issue by Mikiloo** [panx27/amr-reader#3]
The paper you recite gave a web service of entity linking,but the website"http://blender02.cs.rpi.edu:3300"
turns to '404,not found' ,that's a pity.

**Comment by panx27** [comment]
I don't have the permission to access the port anymore. We should put stable urls in our papers in the future. Anyway, here is the new url: http://panx27.github.io/amr
We also have a amr linker api now: http://panx27.github.io/amr_api
